# Generated by Django 4.1.5 on 2023-02-12 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='votes',
        ),
        migrations.AddField(
            model_name='choice',
            name='comments',
            field=models.IntegerField(default=0),
        ),
    ]
